"""Add package contents field

Revision ID: 1285478e434
Revises: 4d3c1febfff
Create Date: 2015-03-02 20:44:44.064389

"""

# revision identifiers, used by Alembic.
revision = '1285478e434'
down_revision = '4d3c1febfff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('contents', sa.Unicode(length=2048), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'contents')
    ### end Alembic commands ###
