"""Add package objects

Revision ID: 1fc38fa913a
Revises: None
Create Date: 2014-10-11 13:24:19.286627

"""

# revision identifiers, used by Alembic.
revision = '1fc38fa913a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
