"""Add 'updated' to packages

Revision ID: 2ca4511880b
Revises: 1fc38fa913a
Create Date: 2014-10-11 13:29:07.675201

"""

# revision identifiers, used by Alembic.
revision = '2ca4511880b'
down_revision = '1fc38fa913a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'updated')
    ### end Alembic commands ###
