"""Fix dependency link

Revision ID: 4d3c1febfff
Revises: 2c9bcf7f568
Create Date: 2014-10-11 18:09:38.912819

"""

# revision identifiers, used by Alembic.
revision = '4d3c1febfff'
down_revision = '2c9bcf7f568'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_dependencies', sa.Column('dependency_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_dependencies', 'dependency_id')
    ### end Alembic commands ###
